#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

readonly DOCKER_IMAGE_NAME="palm"
readonly DOCKER_FILE="$repo_root/docker/Dockerfile"
readonly DOCKER_USER="palm"

docker build \
    -t "$DOCKER_IMAGE_NAME" \
    -f "$DOCKER_FILE" \
    --build-arg=USERNAME="$DOCKER_USER" \
    "$repo_root/docker" 1>&2
