#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

readonly DOCKER_USER="palm"
docker run --rm -it \
    -v "${repo_root}:/home/${DOCKER_USER}/palm" \
    -w "/home/${DOCKER_USER}/palm" palm
